crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from lead.views import home, Signupviews
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', Signupviews.as_view(), name='signup'),

    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
    path('password_reset_done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('lead/', include('lead.urls', namespace='lead')),
    path('agent/', include('agent.urls', namespace='agent')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          documetn_root=settings.STATIC_ROOT)

lead/urls.py
from django.urls import path
from.views import AssignagentView, LeadCreateviews, LeadDeleteviews, LeadDetailviews, LeadListviews, LeadUpdateviews, CategoryListView, CategoryDetailView, CategoryUpdateView

app_name = 'leads'

urlpatterns = [
    path("lead_list/", LeadListviews.as_view(), name='lead_list'),
    path("lead_detail/<int:pk>", LeadDetailviews.as_view(), name='lead_detail'),
    path("category_detail/<int:pk>",
         CategoryDetailView.as_view(), name='category_detail'),
    path("lead_create/", LeadCreateviews.as_view(), name='lead_create'),
    path("category_list/", CategoryListView.as_view(), name='category_list'),
    path("assign_agent/<int:pk>", AssignagentView.as_view(), name='assign_agent'),
    path("lead_update/<int:pk>", LeadUpdateviews.as_view(), name='lead_update'),
    path("category_update/<int:pk>",
         CategoryUpdateView.as_view(), name='category_update'),
    path("lead_delete/<int:pk>", LeadDeleteviews.as_view(), name='lead_delete'),
]

lead/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.db.models.deletion import CASCADE

# Create your models here.


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(
        'Agent', on_delete=models.SET_NULL, blank=True, null=True)
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.first_name


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

lead/forms.py
from django.forms import ModelForm, fields
from django import forms
from .models import Lead, Agent, Category
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

User = get_user_model()


class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ['first_name', 'last_name', 'age', 'agent']


class CustmusercreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
        )

lead/views.py
from django.db.models import query
from django.db.models.query import QuerySet
from django.forms import forms
from django.shortcuts import render, reverse
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_protect
from django.views.generic.list import ListView
from .models import Lead, Category
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AssignAgentForm, LeadForm, CustmusercreationForm, CategoryModelForm
from django.template import RequestContext, context
from django.core.mail import send_mail
from agent.mixins import OrganisrorLoginRequiredMixin
# Create your views here.


class Signupviews(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustmusercreationForm

    def get_success_url(self):
        return reverse('login')


class home(generic.TemplateView):
    template_name = 'home.html'


class LeadListviews(LoginRequiredMixin, generic.ListView):
    template_name = 'lead/lead_list.html'
    context_object_name = 'leads'

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(
                organisation=user.agent.organisation, agent__isnull=False)
            queryset = queryset.filter(agent__user=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadListviews, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile,
                agent__isnull=True
            )
            context.update({
                'unassigned_leads': queryset
            })
        return context


class LeadDetailviews(LoginRequiredMixin, generic.DetailView):
    template_name = 'lead/lead_detail.html'
    context_object_name = 'leads'

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(
                organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=self.request.user)
        return queryset

    def lead_detail(request, pk):
        leads = Lead.objects.get(id=pk)
        return render(request, 'lead/lead_detail.html', {{'leads': leads}})


class LeadCreateviews(OrganisrorLoginRequiredMixin, generic.CreateView):
    template_name = 'lead/lead_create.html'
    form_class = LeadForm

    def get_success_url(self):
        return reverse('leads:lead_list')

    def form_valid(self, form):
        send_mail(
            subject='A lead has bean created',
            message='Go to side see the new lead',
            from_email='test23@gmail.com',
            recipient_list=['test12@gmail.com']
        )
        return super(LeadCreateviews, self).form_valid(form)


class LeadUpdateviews(OrganisrorLoginRequiredMixin, generic.UpdateView):
    template_name = 'lead/lead_update.html'
    form_class = LeadForm

    def lead_update(request, pk):
        lead = Lead.objects.get(id=pk)
        return render(request, 'lead/lead_update.html', {{'leads': lead}})

    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile)

    def get_success_url(self):
        return reverse('lead:lead_list')


class LeadDeleteviews(OrganisrorLoginRequiredMixin, generic.DeleteView):
    template_name = 'lead/lead_delete.html'
    queryset = Lead.objects.all()
    forms_class = LeadForm

    def lead_update(request, pk):
        lead = Lead.objects.all()
        return render(request, 'lead/lead_delete.html', {{'leads': lead}})

    def get_success_url(self) -> str:
        return reverse('lead:lead_list')


class AssignagentView(OrganisrorLoginRequiredMixin, generic.FormView):
    template_name = "lead/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignagentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignagentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = 'lead/category_list.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Lead.objects.filter(
                organisation=user.agent.organisation
            )

        context.update({
            "unassigned_lead_count": queryset.filter(category__isnull=True).count()
        })
        return context

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "lead/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset


class CategoryUpdateView(OrganisrorLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/category_update.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("leads:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset

lead/templates/lead/assign_agent.html
{% extends "base.html" %}

{% block content %}
    <hr>
    <h1>Assign an agent this lead</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">submit</button>
    </form>
{% endblock content %}

lead/templates/lead/category_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
            {{ category.name }}
        </h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These are the leads under this category
        </p>
        <a href="#" class="hover:text-blue-500">Update</a>
        <a href="#" class="hover:text-blue-500">Delete</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                    First Name
                </th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">
                    Last Name
                </th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all %}
                <tr>
                    <td class="px-4 py-3">
                      <a class="hover:text-blue-500" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }}</a>
                    </td>
                    <td class="px-4 py-3">{{ lead.last_name }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

lead/templates/lead/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These categories segment the leads
        </p>
        <a href="#" class="hover:text-blue-500">Create a category</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">Lead Count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td class="px-4 py-3">Unassigned</td>
                <td class="px-4 py-3">{{unassigned_lead_count}}</td>
            </tr>
            {% for category in category_list %}
                <tr>
                    <td class="px-4 py-3">
                      <a href="{% url 'lead:category_detail' category.pk %}" class="hover:text-blue-500" >{{ category.name }}</a>
                    </td>
                    <td class="px-4 py-3">TODO count</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

lead/templates/lead/category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:category-list' %}">Go back to categories</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Update {{ object.name }}</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

lead/templates/lead/lead_create.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">submit</button>
    </form>
{% endblock content %}

lead/templates/lead/lead_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Are you sure you want to delete</h1>
    <h2>{{lead.first_name}}</h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">delete</button>
    </form>
{% endblock content %}

lead/templates/lead/lead_detail.html
{% extends "base.html" %}

{% block content %}

    <section class="text-gray-600 body-font overflow-hidden">
            <div class="container px-5 py-24 mx-auto">
                <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">CRM</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{leads.first_name}} {{leads.last_name}}</h1>
                    <div class="flex mb-4">
                    <a href="{% url 'leads:category_update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'leads:lead_delete' leads.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Delete</a>
                    <a href="{% url 'leads:lead_update' leads.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
                    </div>
                    <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
                    <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Color</span>
                    <span class="ml-auto text-gray-900">Blue</span>
                    </div>
                    <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Size</span>
                    <span class="ml-auto text-gray-900">Medium</span>
                    </div>
                    <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Quantity</span>
                    <span class="ml-auto text-gray-900">4</span>
                    </div>
                    <div class="flex">
                    <span class="title-font font-medium text-2xl text-gray-900">{{leads.age}}</span>
                    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
                    <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                        <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                        </svg>
                    </button>
                    </div>
                </div>
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
                </div>
            </div>
    </section>

{% endblock content %}

lead/templates/lead/lead_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-600 body-font">
            <div class="container px-5 py-24 mx-auto flex flex-wrap">
                <div class="w-full mb-6 py-6 flex justify-between item-center border-b border-gary-200" >
                    <div>
                        <h1 class ='text-4xl text-gray-800' >Leads</h1>
                        <div>
                            <a class = 'text-gray-500 hover:text-blue-500 ' href="{% url 'leads:category_list' %}">Category</a>
                        </div>
                    </div>
                    {% if request.user.is_organisor %}


                        <div>
                            <a class = 'text-gray-500 hover:text-blue-500 ' href="{% url 'leads:lead_create' %}">crate new lead</a>
                        </div>
                    {% endif %}
                </div>
                <hr>
                <div class="flex flex-wrap -m-4">
                    {% for lead in leads %}
                        <div class="p-4 lg:w-1/2 md:w-full">
                            <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                                    </svg>
                                </div>
                                <div class="flex-grow">
                                    <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead.last_name}}</h2>
                                    <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine..</p>
                                    <a href ="{% url 'leads:lead_detail' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">Learn More
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                                    </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}    
                </div>
                {% if unassigned_leads.exists %}
                    <div class="mt-5 flex flex-wrap -m-4">
                        <div class= 'p-4 w-full'>
                            <h1  class ='text-4xl text-gray-800' >Unassigned Leads</h1>
                        </div>
                        {% for lead in unassigned_leads %}
                            
                            <div class="p-4 lg:w-1/2 md:w-full">
                                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                        <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                                        </svg>
                                    </div>
                                    <div class="flex-grow">
                                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead.last_name}}</h2>
                                        <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine..</p>
                                        <a href ="{% url 'leads:assign_agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">Learn More
                                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                                        </svg>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}               
                    </div>
                {% endif %}    
            </div>      
    </section>
{% endblock content %}

lead/templates/lead/lead_update.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">submit</button>
    </form>
{% endblock content %}