agent/urls.py
from django.urls import path
from .views import AgentCreate, AgentDelete, AgentDetail, AgentList, AgentUpdate
app_name = 'agent'

urlpatterns = [
    path('', AgentList.as_view(), name='agent_list'),
    path('agent_list/', AgentList.as_view(), name='agent_list'),
    path('agent_create/', AgentCreate.as_view(), name='agent_create'),
    path('agent_detail/<pk>', AgentDetail.as_view(), name='agent_detail'),
    path('agent_update/<pk>', AgentUpdate.as_view(), name='agent_update'),
    path('agent_delete/<pk>', AgentDelete.as_view(), name='agent_delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from lead.views import home, Signupviews
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', Signupviews.as_view(), name='signup'),

    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
    path('password_reset_done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('lead/', include('lead.urls', namespace='lead')),
    path('agent/', include('agent.urls', namespace='agent')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          documetn_root=settings.STATIC_ROOT)

agent/models.py
from django.db import models

# Create your models here.

agent/forms.py
# from crm.lead.models import User
from django.db.models import fields
# from crm.lead.forms import LeadForm
from django import forms
from django.forms import ModelForm
from django.contrib.auth import get_user_model
# from django.contrib.auth import get_user_model

user = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = user
        fields = ('email', 'username', 'first_name', 'last_name', )

agent/views.py
# from crm.lead.models import UserProfile
from django.core.mail import send_mail
from django.db.models.query import QuerySet
from django.http import request
from django.shortcuts import render
from lead.models import Agent
from django.views import generic
from .forms import AgentModelForm
from django.shortcuts import reverse
from .mixins import OrganisrorLoginRequiredMixin
# Create your views here.
import random


class AgentList(OrganisrorLoginRequiredMixin, generic.ListView):
    template_name = 'agent/agent_list.html'
    context_object_name = "agents"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreate(OrganisrorLoginRequiredMixin, generic.CreateView):
    template_name = 'agent/agent_create.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agent:agent_list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f'{random.randint(0, 1000)}')
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )
        # agent.organisation = self.request.user.userprofile
        # agent.save()
        send_mail(
            subject='your invaited to be agent',
            message='your aad to be agent',
            from_email='test234@test.com',
            recipient_list=[user.email],
        )
        return super(AgentCreate, self).form_valid(form)


class AgentDetail(OrganisrorLoginRequiredMixin, generic.DetailView):
    template_name = 'agent/agent_detail.html'
    context_object_name = 'agent'

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def agentdetail(request, pk):
        agent = Agent.objects.get(id=pk)
        return render(request, 'agen/agent_detail.html', {'agent': agent})


class AgentUpdate(OrganisrorLoginRequiredMixin, generic.UpdateView):
    template_name = 'agent/agent_update.html'
    form_class = AgentModelForm

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_success_url(self) -> str:
        return reverse('agent:agent_list')

    def agent_update(request, pk):
        agent = Agent.objects.get(id=pk)
        return render(request, 'agent/agent_update', {'agent': agent})


class AgentDelete(OrganisrorLoginRequiredMixin, generic.DeleteView):
    template_name = 'agent/agent_delete.html'
    context_object_name = 'agent'

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def agent_delete(request, pk):
        agent = Agent.objects.get(id=pk)
        return render(request, 'agent/agent_delete.html', {'agent': agent})

    def get_success_url(self) -> str:
        return reverse('agent:agent_list')

agent/templates/agent/agent_create.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">submit</button>
    </form>
{% endblock content %}

agent/templates/agent/agent_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Agent</h1>
    <p>Are sure Agent delete </p>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Delete</button>
    </form>
{% endblock content %}

agent/templates/agent/agent_detail.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
        
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">sdf</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}</h1>
            <div class="flex mb-4">
            <a href="{% url 'agent:agent_update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
            <a href={% url 'agent:agent_delete' agent.pk %} class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Delete</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
            </div>
            <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
            <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Color</span>
            <span class="ml-auto text-gray-900">Blue</span>
            </div>
            <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Size</span>
            <span class="ml-auto text-gray-900">Medium</span>
            </div>
            <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Quantity</span>
            <span class="ml-auto text-gray-900">4</span>
            <span class="ml-auto text-gray-900">{{agent.organisation}}</span>
            </div>
            <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                </svg>
            </button>
            </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
        </div>
    </div>
    </section>
{% endblock content %}

agent/templates/agent/agent_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between item-center border-b border-gary-200" >
                <div>
                    <h1 class ='text-4xl text-gray-800' >Agents</h1>
                </div>
                <div>
                    <a class = 'text-gray-500 hover:text-blue-500 ' href="{% url 'agent:agent_create' %}">crate new Agent</a>
                </div>
            </div>
            
            <hr/>
            <div class="flex flex-wrap -m-4">
                {% for agent in agents %}
                    <div class="p-4 lg:w-1/2 md:w-full">
                        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                                </svg>
                            </div>
                            <div class="flex-grow">
                                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}</h2>
                                <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
                                <a href="{% url 'agent:agent_detail' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">View More
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

agent/templates/agent/agent_update.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">submit</button>
    </form>
{% endblock content %}